export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_CATS_PENDING = 'REQUEST_CATS_PENDING';
export const REQUEST_CATS_SUCCESS = 'REQUEST_CATS_SUCCESS';
export const REQUEST_CATS_FAILED = 'REQUEST_CATS_FAILED';